service: dgt-dss-VehicleLookup-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-2
  timeout: 30
  role: arn:aws:iam::336210585422:role/digital-dev-lambda
  deploymentBucket:
    name: smartcar-poc
  deploymentPrefix: Lambda
  memorySize: 512

#define the Lambda functions
functions:
  cb:
    handler: vehicleLookup.handler
    description: Insert scop with VIN of User.
    name: smart-car-VehicleLookup-api
    events:
      - http: 
          path: '/vehicleLookup'
          method: POST
          cors: true
plugins:
  - serverless-offline
